# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef9a65d481a0198fde85d7f75ef478561936d71537c68c4c3612cc5c5fc90fa9f423233263d831b25f1c6f019a847d21d8cef857ce5fd1323e162743ae1d48b3

test:
  secret_key_base: e33c55f4cdfa4b07e944e41fd5c8e295281eed325972cd772c6a586e0047677d98579660a3e22421b118d2714df889f648f53563b97d0de9c5e34b15b77157c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
